version: '3.9'

networks:
  biogenom-network:
    driver: bridge

services:
  postgres:
    container_name: biogenom-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: biogenom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - biogenom-postgres-data:/var/lib/postgresql/data
    networks:
      - biogenom-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  biogenom.api:
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    image: ${DOCKER_REGISTRY-}biogenomapi
    build:
      context: .
      dockerfile: BioGenom.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - biogenom-network

volumes:
  biogenom-postgres-data: